name: segswap
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.2.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - bzip2=1.0.8
  - ca-certificates=2023.5.7
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=1.2.0
  - ipykernel=6.15.0
  - ipython=8.14.0
  - jedi=0.18.2
  - jupyter_client=7.3.4
  - jupyter_core=5.3.1
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - matplotlib-inline=0.1.6
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - openssl=3.0.9
  - packaging=23.1
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - platformdirs=3.8.0
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.15.1
  - python=3.10.11
  - python-dateutil=2.8.2
  - python_abi=3.10
  - readline=8.2
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tk=8.6.12
  - traitlets=5.9.0
  - typing-extensions=4.6.3
  - typing_extensions=4.6.3
  - wcwidth=0.2.6
  - xz=5.4.2
  - zeromq=4.3.4
  - zlib=1.2.13
  - pip:
    - absl-py==1.4.0
    - appdirs==1.4.4
    - cachetools==5.3.1
    - certifi==2023.5.7
    - charset-normalizer==3.1.0
    - click==8.1.4
    - cmake==3.26.4
    - contourpy==1.1.0
    - cycler==0.11.0
    - debugpy==1.5.1
    - decord==0.6.0
    - docker-pycreds==0.4.0
    - filelock==3.12.2
    - fonttools==4.40.0
    - gitdb==4.0.10
    - gitpython==3.1.31
    - google-auth==2.22.0
    - google-auth-oauthlib==1.0.0
    - grpcio==1.56.2
    - idna==3.4
    - imageio==2.31.5
    - jinja2==3.1.2
    - joblib==1.2.0
    - jupyter-core==5.3.1
    - kiwisolver==1.4.4
    - kornia==0.6.12
    - lazy-loader==0.3
    - lit==16.0.6
    - markdown==3.4.3
    - markupsafe==2.1.3
    - matplotlib==3.7.1
    - mpmath==1.3.0
    - natsort==8.4.0
    - networkx==3.1
    - numpy==1.25.0
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nvtx-cu11==11.7.91
    - oauthlib==3.2.2
    - opencv-python==4.7.0.72
    - pandas==2.0.3
    - pathtools==0.1.2
    - pillow==9.5.0
    - pip==23.1.2
    - protobuf==4.23.4
    - psutil==5.9.0
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pycocotools==2.0.6
    - pyparsing==3.1.0
    - pytz==2023.3
    - pyyaml==6.0
    - pyzmq==25.1.0
    - requests==2.31.0
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - scikit-image==0.22.0
    - scikit-learn==1.2.2
    - scipy==1.11.0
    - sentry-sdk==1.27.1
    - setproctitle==1.3.2
    - setuptools==67.8.0
    - smmap==5.0.0
    - sympy==1.12
    - tensorboard==2.13.0
    - tensorboard-data-server==0.7.1
    - tensorboardx==2.6.1
    - threadpoolctl==3.1.0
    - tifffile==2023.9.26
    - torch==2.0.1
    - torchvision==0.15.2
    - tornado==6.1
    - tqdm==4.65.0
    - triton==2.0.0
    - tzdata==2023.3
    - urllib3==1.26.16
    - wandb==0.15.5
    - werkzeug==2.3.6
    - wheel==0.38.4
